### ISSUE TITLE
cannot patched the ELF

### ISSUE THREAD

**Issue by sinkthemall** [robbert1978/alt-pwninit#4] opened 2023-05-09 06:50 UTC
![image](https://user-images.githubusercontent.com/92171234/237016812-3893063f-549e-4857-be46-2a2f2622d688.png)

**Comment by th3-5had0w** [comment] 2023-05-09 06:53
way too dank pepega

**Comment by robbert1978** [comment] 2023-05-09 08:27
What is the version of the libc ? Btw =)) the remote server also uses libc 2.35
![image](https://user-images.githubusercontent.com/31349426/237039264-0353783e-72aa-4060-8001-372368317427.png)

**Comment by sinkthemall** [comment] 2023-05-09 08:32
![image](https://user-images.githubusercontent.com/92171234/237040405-fd256eec-3ff4-47c2-a0da-4df7e7fe4369.png)

**Comment by robbert1978** [comment] 2023-05-09 08:35
I found you had used libc 2.34 (in the screenshot), I tested and it cloud run on my machine.
P/s : please run `./ld-linux-x86-64.so.2 ./libc.so.6` to give me the version of libc
![image](https://user-images.githubusercontent.com/31349426/237040638-ce496dfc-1606-4c44-a926-ce1c5962e1c8.png)

**Comment by sinkthemall** [comment] 2023-05-09 08:40
ah yes, the version of glibc is 2.34
![image](https://user-images.githubusercontent.com/92171234/237042588-5975b33b-cdb9-42fe-a92d-e21741554cec.png)

**Comment by robbert1978** [comment] 2023-05-09 08:41
Lol, try to run `pwninit.py --bin chall --libc libc.so.6`, it works on my machine.

**Comment by sinkthemall** [comment] 2023-05-09 08:44
still not working :((
![image](https://user-images.githubusercontent.com/92171234/237043533-352f6d8a-fd7d-4a3b-b504-97dfd9582c92.png)

**Comment by robbert1978** [comment] 2023-05-09 08:46
Ah,  WSL, can't make symlink in Windows NTFS format disk.
Try to use in Linux VM not WSL,

**Comment by th3-5had0w** [comment] 2023-05-10 01:40
What's the problem with making symlink? I don't see any log related to symlink problem.
@sinkthemall @robbert1978

**Comment by robbert1978** [comment] 2023-05-10 02:20
In some libc deb packages, ld-linux-x86-64.so.2 is symlink to ld-2.xx.so, I think it will be broken when trying to open it on Windows

**Comment by th3-5had0w** [comment] 2023-05-10 02:38
Hmm, I don't think so, because from the logs I see they're fail because no `libc-2.34.so` is found or it fails at patchelf stage?
That being said, it must fails at the first time the deb file is extracted because symlink will not be resolved in WSL and the file will fails to copy `ld-linux-x86-64.so.2`, right?

**Comment by robbert1978** [comment] 2023-05-10 04:33
Hmm, maybe there is an issue with patchelf ? I will try testing in WSL to find the issue.

**Comment by robbert1978** [comment] 2023-05-10 06:24
@sinkthemall can you give me your libc file ?

**Comment by sinkthemall** [comment] 2023-05-10 08:49
sure 
here is my libc file: 
[libc.so.zip](https://github.com/robbert1978/alt-pwninit/files/11439879/libc.so.zip)

**Comment by robbert1978** [comment] 2023-05-10 10:14
@sinkthemall 
Check our new scripts.
![image](https://github.com/robbert1978/alt-pwninit/assets/31349426/09e94742-026a-4679-86a3-ba0d1e5331af)

**Comment by sinkthemall** [comment] 2023-05-10 10:41
I don't want to disappoint you, but it still not work
![image](https://github.com/robbert1978/alt-pwninit/assets/92171234/e02b07a1-365f-43f2-aa3d-b9c0a17b1311)

**Comment by robbert1978** [comment] 2023-05-10 12:22
Try to run `patchelf --set-rpath . --set-interpreter ./ld-linux-x86-64.so.2 --output chall_patched ./chall`

**Comment by sinkthemall** [comment] 2023-05-10 14:10
![image](https://github.com/robbert1978/alt-pwninit/assets/92171234/571038bc-3700-4b79-9222-25cc3acef0c5)
patchelf doesn't have --output option

**Comment by robbert1978** [comment] 2023-05-10 14:17
Try to update `patchelf`, both `patchelf` in WSL and `Ubuntu 22.04` VMware in my machine have that option.
P/s: Check your  `patchelf` version
![image](https://github.com/robbert1978/alt-pwninit/assets/31349426/ae711776-05f2-4461-a3bb-0826ac6ce972)
![image](https://github.com/robbert1978/alt-pwninit/assets/31349426/7ea2b34c-4624-4c2b-b8d4-558b64545ee2)
![image](https://github.com/robbert1978/alt-pwninit/assets/31349426/077c4084-33bc-4947-9c32-4bc2af465c64)

**Comment by th3-5had0w** [comment] 2023-05-10 15:07
so it is a patchelf problem
and also the failure log has been suppressed in commit [70d6fdfe25847122b7c5f7851d8f77ada9ed6c03](https://github.com/robbert1978/alt-pwninit/commit/70d6fdfe25847122b7c5f7851d8f77ada9ed6c03)

the problem is considered done

**Closed as completed by th3-5had0w** 2023-05-10 15:07 UTC
Labels: bug

**Comment by sinkthemall** [comment] 2023-05-10 15:43
@robbert1978  how did you download the version 0.14.3, I tried to install but this happen
![image](https://github.com/robbert1978/alt-pwninit/assets/92171234/bfce7248-6c05-4992-8f2c-4856a2f8af71)
It seem like I need to downgrade libc to install it, what should I do?

**Comment by robbert1978** [comment] 2023-05-10 15:47
lol, just install normally, do not downgrade libc, btw, did you run `make setup` ?

**Comment by robbert1978** [comment] 2023-05-11 00:46
@sinkthemall 
Version of libc on your wsl is 2.31, you should upgrade your system rather than trying to downgrade libc :D
![image](https://github.com/robbert1978/alt-pwninit/assets/31349426/29f4b4f3-3554-4920-830f-1646a5eb2d1b)

**Comment by sinkthemall** [comment] 2023-05-11 03:09
![image](https://github.com/robbert1978/alt-pwninit/assets/92171234/61bca375-8574-4c2a-8730-2a22920c18b9)
I updated ubuntu and it works, tks alot
